### ISSUE TITLE
Checkbox private tout le temps active

### ISSUE THREAD

**Issue by Khady** [dhoko/ShaarliTemplate#1]
Bonjour,

Dans la fenetre d'ajout de lien qui s'affiche grace au bouton `Shaare link`, la checkbox Private est tout le temps active, quelle que soit ma configuration de shaarli. Je n'ai pas ce probleme avec le dossier tpl de base.

**Comment by jeekajoo** [comment]
J'allais reporter le même bug :)

**Comment by dhoko** [comment]
Salut,

Voilà j'ai corrigé le problème dans ce commit 1c6b486b0ac8c2ae02fe3e83667ed4774e58d470 il suffit de pull master pour avoir la checkbox fonctionnelle.
- Nouveau lien : checkbox chochée
- Si le lien est privé : checkbox cochée
- Si le lien est public : checkbox non cochée

Voilà c'est le comportement normal ;-)
Dhoko.

**Comment by Khady** [comment]
J'ai toujours le même comportement malgré le changement.
Par contre si je remplace
`{if condition="$GLOBALS['privateLinkByDefault']==true  || $link.private && !$link_is_new || $link_is_new "}`
par
`{if condition="$GLOBALS['privateLinkByDefault']==true"}`
J'ai le comportement attendu.

Cela doit poser problème pour l'édition par contre, je ne sais pas exactement ce qu'il faudrait ajouter.

`{if condition="($link_is_new && $GLOBALS['privateLinkByDefault']==true) || $link.private == true"}`
me parait bien.

**Comment by dhoko** [comment]
Ha ok,je sais pourquoi ça ne fonctionnait pas chez moi, je n'avais pas vu l'option dans `?do=configure`
Je merge.

**Comment by Khady** [comment]
Merci pour la réaction rapide et bravo pour le boulot, c'est vraiment sympa à l'utilisation.

**Comment by dhoko** [comment]
De rien. Et merci pour la pull request au passage, quand même
