### ISSUE TITLE
Posts sur la colonne de gauche seulement

### ISSUE THREAD

**Issue by jlnbdt** [dhoko/ShaarliTemplate#3]
Hello,

Je viens d'installer le _template_ sur le fork de Shaarli de abeaumet (ajoutant le support de Markdown).

Les « posts » ne sont affichés que sur la colonne de gauche, comme montré sur la capture jointe.

![capture](https://f.cloud.github.com/assets/6383095/1896574/1980fdbe-7ba8-11e3-84cf-837ad41decd3.png)

Testé avec Firefox et Chromium. Résolution 1280x800

Merci !

**Comment by jlnbdt** [comment]
Je viens de tester sur un moniteur externe : les deux colonnes apparaissent bien. C'est donc bien lié à la résolution, jugée trop étroite pour 2 colonnes ?

**Comment by dhoko** [comment]
Oui c'est ce que je pensais aussi, ton viewport est de 1280px et ça ne passe pas super bien. Je vais render plus souple l'affichage pour qu'il ne tienne plus compte des breakpoints en px.

Je n'ai plus d'env de test sous la main pour le moment, j'en monte un et je regarde.

**Comment by dhoko** [comment]
Voilou, c'est corrigé ! Merci pour ton retour.
