### ISSUE TITLE
Largeur de la boîte sur la page permalink

### ISSUE THREAD

**Issue by jlnbdt** [dhoko/ShaarliTemplate#5]
Hello again,

J'ai remarqué un comportement erratique de l'adaptation de la largeur de la « boîte blanche » sur la page d'un enregistrement unique (celle que l'on suit _via_ le permalink).

En 849px de largeur, l'apparence est normale :

![849_les_femmes_bousculent_le_poids_des_normes_masculines_-_veille_genre_ _fminisme_-_2014-01-13_08 28 15](https://f.cloud.github.com/assets/6383095/1898620/ebb6c7ba-7c24-11e3-9783-97afe5076202.png)

À partir de 850px, un décalage se produit (ici en 863px) :

![863_les_femmes_bousculent_le_poids_des_normes_masculines_-_veille_genre_ _fminisme_-_2014-01-13_08 28 37](https://f.cloud.github.com/assets/6383095/1898627/29ba5cc0-7c25-11e3-96d8-c3ed4eb09900.png)

Sur l'image suivante, c'est même pire : plus la résolution augmente, plus la largeur diminue. Ici en 1165px :

![1165_de_dsk__lapollonide_la_marchandisation_du_corps_des_femmes_-_veille_genre_ _fminisme_-_2014-01-13_08 29 52](https://f.cloud.github.com/assets/6383095/1898636/543f881c-7c25-11e3-9d12-78879f62d9f4.png)

Enfin — je ne sais pas si c'est lié — il arrive que la boîte chevauche le pied de page. C'est un comportement que je ne parviens pas à reproduire de manière systématique (je me demande s'il n'est pas lié à la présence d'une image dans la description). En voici un exemple :

![les_hommes__la_hauteur_une_longue_inquitude_-_veille_genre_ _fminisme_-_2014-01-13_08 37 15](https://f.cloud.github.com/assets/6383095/1898642/b9220232-7c25-11e3-9825-9ddbb5e2d0c9.png)

Encore merci !

**Comment by dhoko** [comment]
Le soucis venait du fait que Masonry était lancé si on possédait uniquement un post, ce qui est inutile. C'est corrigé, merci :)
